# Generated by Django 2.2.7 on 2019-11-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_auto_20191115_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(to='product_manager.Product')),
            ],
        ),
    ]
