# Generated by Django 2.2.7 on 2019-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='goods',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tel',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True, verbose_name='Date of making a purchase '),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=2, max_length=155),
            preserve_default=False,
        ),
    ]
