# Generated by Django 2.2.7 on 2019-11-18 16:01

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0004_auto_20191117_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
