# Generated by Django 2.2.7 on 2019-11-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0005_auto_20191118_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(to='product_manager.Product'),
        ),
    ]
