# Generated by Django 2.2.7 on 2019-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0009_auto_20191118_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name=range(1, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(verbose_name=range(1, 8)),
        ),
    ]
